#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x1EEF53D38A3A9C67 (andreas.boll.dev@gmail.com)
#
Name     : mesa-demos
Version  : 8.3.0
Release  : 12
URL      : ftp://ftp.freedesktop.org/pub/mesa/demos/8.3.0/mesa-demos-8.3.0.tar.gz
Source0  : ftp://ftp.freedesktop.org/pub/mesa/demos/8.3.0/mesa-demos-8.3.0.tar.gz
Source99 : ftp://ftp.freedesktop.org/pub/mesa/demos/8.3.0/mesa-demos-8.3.0.tar.gz.sig
Summary  : Mesa demos and tools incl. glxinfo + glxgears
Group    : Development/Tools
License  : MIT
Requires: mesa-demos-bin = %{version}-%{release}
Requires: mesa-demos-data = %{version}-%{release}
BuildRequires : freeglut-dev
BuildRequires : glew-dev
BuildRequires : pkgconfig(egl)
BuildRequires : pkgconfig(freetype2)
BuildRequires : pkgconfig(gl)
BuildRequires : pkgconfig(glesv1_cm)
BuildRequires : pkgconfig(glesv2)
BuildRequires : pkgconfig(glew)
BuildRequires : pkgconfig(glu)
BuildRequires : pkgconfig(libdrm)
BuildRequires : pkgconfig(wayland-client)
BuildRequires : pkgconfig(wayland-egl)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xext)

%description
/*
*	For the software in this directory
* ALL RIGHTS RESERVED
* Permission to use, copy, modify, and distribute this software for
* any purpose and without fee is hereby granted, provided that the above
* copyright notice appear in all copies and that both the copyright notice
* and this permission notice appear in supporting documentation, and that
* the name of Silicon Graphics, Inc. not be used in advertising
* or publicity pertaining to distribution of the software without specific,
* written prior permission.
*
* THE MATERIAL EMBODIED ON THIS SOFTWARE IS PROVIDED TO YOU "AS-IS"
* AND WITHOUT WARRANTY OF ANY KIND, EXPRESS, IMPLIED OR OTHERWISE,
* INCLUDING WITHOUT LIMITATION, ANY WARRANTY OF MERCHANTABILITY OR
* FITNESS FOR A PARTICULAR PURPOSE.  IN NO EVENT SHALL SILICON
* GRAPHICS, INC.  BE LIABLE TO YOU OR ANYONE ELSE FOR ANY DIRECT,
* SPECIAL, INCIDENTAL, INDIRECT OR CONSEQUENTIAL DAMAGES OF ANY
* KIND, OR ANY DAMAGES WHATSOEVER, INCLUDING WITHOUT LIMITATION,
* LOSS OF PROFIT, LOSS OF USE, SAVINGS OR REVENUE, OR THE CLAIMS OF
* THIRD PARTIES, WHETHER OR NOT SILICON GRAPHICS, INC.  HAS BEEN
* ADVISED OF THE POSSIBILITY OF SUCH LOSS, HOWEVER CAUSED AND ON
* ANY THEORY OF LIABILITY, ARISING OUT OF OR IN CONNECTION WITH THE
* POSSESSION, USE OR PERFORMANCE OF THIS SOFTWARE.
*
* US Government Users Restricted Rights
* Use, duplication, or disclosure by the Government is subject to
* restrictions set forth in FAR 52.227.19(c)(2) or subparagraph
* (c)(1)(ii) of the Rights in Technical Data and Computer Software
* clause at DFARS 252.227-7013 and/or in similar or successor
* clauses in the FAR or the DOD or NASA FAR Supplement.
* Unpublished-- rights reserved under the copyright laws of the
* United States.  Contractor/manufacturer is Silicon Graphics,
* Inc., 2011 N.  Shoreline Blvd., Mountain View, CA 94039-7311.
*
* OpenGL(TM) is a trademark of Silicon Graphics, Inc.
*/

%package bin
Summary: bin components for the mesa-demos package.
Group: Binaries
Requires: mesa-demos-data = %{version}-%{release}

%description bin
bin components for the mesa-demos package.


%package data
Summary: data components for the mesa-demos package.
Group: Data

%description data
data components for the mesa-demos package.


%prep
%setup -q -n mesa-demos-8.3.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1557095836
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1557095836
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
%exclude /usr/bin/arbfplight
%exclude /usr/bin/arbfslight
%exclude /usr/bin/arbocclude
%exclude /usr/bin/arbocclude2
%exclude /usr/bin/array
%exclude /usr/bin/bezier
%exclude /usr/bin/bitmap
%exclude /usr/bin/blinking-teapot
%exclude /usr/bin/bounce
%exclude /usr/bin/brick
%exclude /usr/bin/bump
%exclude /usr/bin/clear-color
%exclude /usr/bin/clear-fbo
%exclude /usr/bin/clear-fbo-scissor
%exclude /usr/bin/clear-fbo-tex
%exclude /usr/bin/clear-random
%exclude /usr/bin/clear-repeat
%exclude /usr/bin/clear-scissor
%exclude /usr/bin/clear-undefined
%exclude /usr/bin/clearspd
%exclude /usr/bin/convolutions
%exclude /usr/bin/copypix
%exclude /usr/bin/copytex
%exclude /usr/bin/createwin
%exclude /usr/bin/cubemap
%exclude /usr/bin/cuberender
%exclude /usr/bin/deriv
%exclude /usr/bin/dinoshade
%exclude /usr/bin/dissolve
%exclude /usr/bin/dlist-begin-call-end
%exclude /usr/bin/dlist-dangling
%exclude /usr/bin/dlist-degenerate
%exclude /usr/bin/dlist-edgeflag
%exclude /usr/bin/dlist-edgeflag-dangling
%exclude /usr/bin/dlist-flat-tri
%exclude /usr/bin/dlist-mat-tri
%exclude /usr/bin/dlist-recursive-call
%exclude /usr/bin/dlist-tri-flat-tri
%exclude /usr/bin/dlist-tri-mat-tri
%exclude /usr/bin/draw2arrays
%exclude /usr/bin/drawarrays
%exclude /usr/bin/drawelements
%exclude /usr/bin/drawelements-large
%exclude /usr/bin/drawoverhead
%exclude /usr/bin/drawpix
%exclude /usr/bin/drawrange
%exclude /usr/bin/engine
%exclude /usr/bin/es2_info
%exclude /usr/bin/es2gears_x11
%exclude /usr/bin/es2tri
%exclude /usr/bin/fbo_firecube
%exclude /usr/bin/fbobind
%exclude /usr/bin/fbotexture
%exclude /usr/bin/fill
%exclude /usr/bin/fire
%exclude /usr/bin/flat-clip
%exclude /usr/bin/fogcoord
%exclude /usr/bin/fplight
%exclude /usr/bin/fragcoord
%exclude /usr/bin/fs-tri
%exclude /usr/bin/fslight
%exclude /usr/bin/fsraytrace
%exclude /usr/bin/gamma
%exclude /usr/bin/gearbox
%exclude /usr/bin/gears
%exclude /usr/bin/geartrain
%exclude /usr/bin/genmipmap
%exclude /usr/bin/geom-outlining-130
%exclude /usr/bin/geom-outlining-150
%exclude /usr/bin/geom-sprites
%exclude /usr/bin/geom-stipple-lines
%exclude /usr/bin/geom-wide-lines
%exclude /usr/bin/gloss
%exclude /usr/bin/glslstateschange
%exclude /usr/bin/gltestperf
%exclude /usr/bin/glthreads
%exclude /usr/bin/glxcontexts
%exclude /usr/bin/glxdemo
%exclude /usr/bin/glxgears_fbconfig
%exclude /usr/bin/glxgears_pixmap
%exclude /usr/bin/glxheads
%exclude /usr/bin/glxpbdemo
%exclude /usr/bin/glxpixmap
%exclude /usr/bin/glxsnoop
%exclude /usr/bin/glxswapcontrol
%exclude /usr/bin/gs-tri
%exclude /usr/bin/gsraytrace
%exclude /usr/bin/identity
%exclude /usr/bin/ipers
%exclude /usr/bin/isosurf
%exclude /usr/bin/line
%exclude /usr/bin/line-clip
%exclude /usr/bin/line-cull
%exclude /usr/bin/line-flat
%exclude /usr/bin/line-smooth
%exclude /usr/bin/line-stipple-wide
%exclude /usr/bin/line-userclip
%exclude /usr/bin/line-userclip-clip
%exclude /usr/bin/line-userclip-nop
%exclude /usr/bin/line-userclip-nop-clip
%exclude /usr/bin/line-wide
%exclude /usr/bin/line-xor
%exclude /usr/bin/lineloop
%exclude /usr/bin/lineloop-clip
%exclude /usr/bin/lineloop-elts
%exclude /usr/bin/linestrip
%exclude /usr/bin/linestrip-clip
%exclude /usr/bin/linestrip-flat-stipple
%exclude /usr/bin/linestrip-stipple
%exclude /usr/bin/linestrip-stipple-wide
%exclude /usr/bin/linktest
%exclude /usr/bin/lodbias
%exclude /usr/bin/long-fixed-func
%exclude /usr/bin/mandelbrot
%exclude /usr/bin/manywin
%exclude /usr/bin/morph3d
%exclude /usr/bin/multiarb
%exclude /usr/bin/multictx
%exclude /usr/bin/multinoise
%exclude /usr/bin/multitex
%exclude /usr/bin/noise
%exclude /usr/bin/noise2
%exclude /usr/bin/offset
%exclude /usr/bin/osdemo
%exclude /usr/bin/osdemo16
%exclude /usr/bin/osdemo32
%exclude /usr/bin/overlay
%exclude /usr/bin/paltex
%exclude /usr/bin/pbdemo
%exclude /usr/bin/pbinfo
%exclude /usr/bin/pgon-mode
%exclude /usr/bin/pixeltest
%exclude /usr/bin/point
%exclude /usr/bin/point-clip
%exclude /usr/bin/point-param
%exclude /usr/bin/point-sprite
%exclude /usr/bin/point-wide
%exclude /usr/bin/point-wide-smooth
%exclude /usr/bin/pointblast
%exclude /usr/bin/pointcoord
%exclude /usr/bin/points
%exclude /usr/bin/poly
%exclude /usr/bin/poly-flat
%exclude /usr/bin/poly-flat-clip
%exclude /usr/bin/poly-flat-unfilled-clip
%exclude /usr/bin/poly-unfilled
%exclude /usr/bin/projtex
%exclude /usr/bin/quad
%exclude /usr/bin/quad-clip
%exclude /usr/bin/quad-clip-all-vertices
%exclude /usr/bin/quad-clip-nearplane
%exclude /usr/bin/quad-degenerate
%exclude /usr/bin/quad-flat
%exclude /usr/bin/quad-offset-factor
%exclude /usr/bin/quad-offset-unfilled
%exclude /usr/bin/quad-offset-units
%exclude /usr/bin/quad-tex-2d
%exclude /usr/bin/quad-tex-3d
%exclude /usr/bin/quad-tex-alpha
%exclude /usr/bin/quad-tex-pbo
%exclude /usr/bin/quad-tex-sub
%exclude /usr/bin/quad-unfilled
%exclude /usr/bin/quad-unfilled-clip
%exclude /usr/bin/quad-unfilled-stipple
%exclude /usr/bin/quads
%exclude /usr/bin/quadstrip
%exclude /usr/bin/quadstrip-clip
%exclude /usr/bin/quadstrip-cont
%exclude /usr/bin/quadstrip-flat
%exclude /usr/bin/ray
%exclude /usr/bin/readpix
%exclude /usr/bin/readpixels
%exclude /usr/bin/reflect
%exclude /usr/bin/renormal
%exclude /usr/bin/samplers
%exclude /usr/bin/samplers_array
%exclude /usr/bin/shadow_sampler
%exclude /usr/bin/shadowtex
%exclude /usr/bin/shape
%exclude /usr/bin/sharedtex
%exclude /usr/bin/sharedtex_mt
%exclude /usr/bin/shtest
%exclude /usr/bin/simplex-noise
%exclude /usr/bin/singlebuffer
%exclude /usr/bin/skinning
%exclude /usr/bin/spectex
%exclude /usr/bin/spriteblast
%exclude /usr/bin/stex3d
%exclude /usr/bin/sub-tex
%exclude /usr/bin/swapbuffers
%exclude /usr/bin/teapot
%exclude /usr/bin/terrain
%exclude /usr/bin/tessdemo
%exclude /usr/bin/tex-quads
%exclude /usr/bin/texaaline
%exclude /usr/bin/texcyl
%exclude /usr/bin/texdemo1
%exclude /usr/bin/texenv
%exclude /usr/bin/teximage
%exclude /usr/bin/texture_from_pixmap
%exclude /usr/bin/textures
%exclude /usr/bin/toyball
%exclude /usr/bin/tri
%exclude /usr/bin/tri-2101010
%exclude /usr/bin/tri-2101010-dlist
%exclude /usr/bin/tri-alpha
%exclude /usr/bin/tri-alpha-tex
%exclude /usr/bin/tri-array-interleaved
%exclude /usr/bin/tri-blend
%exclude /usr/bin/tri-blend-color
%exclude /usr/bin/tri-blend-max
%exclude /usr/bin/tri-blend-min
%exclude /usr/bin/tri-blend-revsub
%exclude /usr/bin/tri-blend-sub
%exclude /usr/bin/tri-clear
%exclude /usr/bin/tri-clip
%exclude /usr/bin/tri-cull
%exclude /usr/bin/tri-cull-both
%exclude /usr/bin/tri-dlist
%exclude /usr/bin/tri-edgeflag
%exclude /usr/bin/tri-edgeflag-array
%exclude /usr/bin/tri-edgeflag-pv
%exclude /usr/bin/tri-fbo
%exclude /usr/bin/tri-fbo-tex
%exclude /usr/bin/tri-fbo-tex-mip
%exclude /usr/bin/tri-flat
%exclude /usr/bin/tri-flat-clip
%exclude /usr/bin/tri-fog
%exclude /usr/bin/tri-fp
%exclude /usr/bin/tri-fp-const-imm
%exclude /usr/bin/tri-lit
%exclude /usr/bin/tri-lit-material
%exclude /usr/bin/tri-logicop-none
%exclude /usr/bin/tri-logicop-xor
%exclude /usr/bin/tri-mask-tri
%exclude /usr/bin/tri-multitex-vbo
%exclude /usr/bin/tri-orig
%exclude /usr/bin/tri-point-line-clipped
%exclude /usr/bin/tri-query
%exclude /usr/bin/tri-repeat
%exclude /usr/bin/tri-rotate
%exclude /usr/bin/tri-scissor-tri
%exclude /usr/bin/tri-square
%exclude /usr/bin/tri-stencil
%exclude /usr/bin/tri-stipple
%exclude /usr/bin/tri-tex
%exclude /usr/bin/tri-tex-1d
%exclude /usr/bin/tri-tex-3d
%exclude /usr/bin/tri-tex-stipple
%exclude /usr/bin/tri-tri
%exclude /usr/bin/tri-unfilled
%exclude /usr/bin/tri-unfilled-clip
%exclude /usr/bin/tri-unfilled-edgeflag
%exclude /usr/bin/tri-unfilled-fog
%exclude /usr/bin/tri-unfilled-point
%exclude /usr/bin/tri-unfilled-smooth
%exclude /usr/bin/tri-unfilled-tri
%exclude /usr/bin/tri-unfilled-tri-lit
%exclude /usr/bin/tri-unfilled-userclip
%exclude /usr/bin/tri-unfilled-userclip-stip
%exclude /usr/bin/tri-userclip
%exclude /usr/bin/tri-viewport
%exclude /usr/bin/tri-z
%exclude /usr/bin/tri-z-9
%exclude /usr/bin/tri-z-clip
%exclude /usr/bin/tri-z-eq
%exclude /usr/bin/trifan
%exclude /usr/bin/trifan-flat
%exclude /usr/bin/trifan-flat-clip
%exclude /usr/bin/trifan-flat-unfilled-clip
%exclude /usr/bin/trifan-unfilled
%exclude /usr/bin/trirast
%exclude /usr/bin/trispd
%exclude /usr/bin/tristrip
%exclude /usr/bin/tristrip-clip
%exclude /usr/bin/tristrip-flat
%exclude /usr/bin/tunnel
%exclude /usr/bin/tunnel2
%exclude /usr/bin/twoside
%exclude /usr/bin/vao_demo
%exclude /usr/bin/vbo
%exclude /usr/bin/vbo-drawarrays
%exclude /usr/bin/vbo-drawarrays-2101010
%exclude /usr/bin/vbo-drawelements
%exclude /usr/bin/vbo-drawrange
%exclude /usr/bin/vbo-noninterleaved
%exclude /usr/bin/vbo-tri
%exclude /usr/bin/vert-or-frag-only
%exclude /usr/bin/vert-tex
%exclude /usr/bin/vertexrate
%exclude /usr/bin/vp-array
%exclude /usr/bin/vp-array-hf
%exclude /usr/bin/vp-array-int
%exclude /usr/bin/vp-clip
%exclude /usr/bin/vp-line-clip
%exclude /usr/bin/vp-tri
%exclude /usr/bin/vp-tri-cb
%exclude /usr/bin/vp-tri-cb-pos
%exclude /usr/bin/vp-tri-cb-tex
%exclude /usr/bin/vp-tri-imm
%exclude /usr/bin/vp-tri-invariant
%exclude /usr/bin/vp-tri-swap
%exclude /usr/bin/vp-tri-tex
%exclude /usr/bin/vp-unfilled
%exclude /usr/bin/vsraytrace
%exclude /usr/bin/wincopy
%exclude /usr/bin/winpos
%exclude /usr/bin/xfont
%exclude /usr/bin/xrotfontdemo
/usr/bin/glinfo
/usr/bin/glsync
/usr/bin/glxgears
/usr/bin/glxinfo

%files data
%defattr(-,root,root,-)
%exclude /usr/share/mesa-demos/arch.rgb
%exclude /usr/share/mesa-demos/bw.rgb
%exclude /usr/share/mesa-demos/geartrain.dat
%exclude /usr/share/mesa-demos/girl.rgb
%exclude /usr/share/mesa-demos/girl2.rgb
%exclude /usr/share/mesa-demos/isosurf.dat
%exclude /usr/share/mesa-demos/reflect.rgb
%exclude /usr/share/mesa-demos/s128.rgb
%exclude /usr/share/mesa-demos/terrain.dat
%exclude /usr/share/mesa-demos/tile.rgb
%exclude /usr/share/mesa-demos/tree2.rgba
%exclude /usr/share/mesa-demos/tree3.rgb
%exclude /usr/share/mesa-demos/wrs_logo.rgb
